### ISSUE TITLE
Recipe App

### ISSUE THREAD

**Issue by Haywayaheadshot** [Goruchie/Recipe-app#22]
We are three (3) coding partners namely; 

@Haywayaheadshot : as team member 1
@taldr27 : as team member 2
@Goruchie : as team member 3

Please click [here](https://github.com/users/Goruchie/projects/4) to view our Kanban board

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Your project is complete!  There is nothing else to say :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Haywayaheadshot** [comment]
@ShadyShawkat Thank you for reviewing our project. Have a nice day
